# Date: 2024-3-1
# Author: Generated by GoCodeo.


import pytest 

from re_edge_gpt.ui.chat.chat_thread import ChatThread, DelegateChat, MESSAGE_QUEUE, PANEL_MESSAGE_QUEUE, DELEGATE_CHAT, EXCEPTION_QUEUE 

from PySide6.QtWidgets import QPlainTextEdit 

from queue import Queue 

from threading import Thread 

import asyncio 

import json 

from pathlib import Path 

class TestChatThread(unittest.TestCase):

	@pytest.mark.parametrize('chat_send_message, locale', [('Hello', 'en-US'), ('How are you?', 'en-GB')])
	def test_chat_thread_initialization(chat_send_message, locale):
	    chat_thread = ChatThread(chat_send_message, locale)
	    assert chat_thread.current_message is None
	    assert chat_thread.chat_send_message == chat_send_message
	    assert chat_thread.locale == locale 


